import { CatalogAttraction } from './catalog.types';

export const demoAttractions: CatalogAttraction[] = [
  {
    provider: 'TICKETMASTER',
    externalId: 'demo-coldplay',
    name: 'Coldplay',
    imageUrl: '/events/aurora-live.png',
    imageAlt: 'Palco contemporaneo iluminado durante um grande show ao vivo',
    category: 'Musica',
    genre: 'Rock',
    subGenre: 'Alternative Rock',
    sourceUrl: null,
    locale: 'en-us',
    upcomingEvents: 18,
  },
  {
    provider: 'TICKETMASTER',
    externalId: 'demo-liniker',
    name: 'Liniker',
    imageUrl: '/events/cena-aberta.png',
    imageAlt: 'Artista em um palco com iluminacao marcante',
    category: 'Musica',
    genre: 'MPB',
    subGenre: null,
    sourceUrl: null,
    locale: 'pt-br',
    upcomingEvents: 5,
  },
  {
    provider: 'TICKETMASTER',
    externalId: 'demo-rock-in-rio',
    name: 'Rock in Rio',
    imageUrl: '/events/pulso-urbano.png',
    imageAlt: 'Grande festival ao ar livre com palco e publico',
    category: 'Festival',
    genre: 'Rock',
    subGenre: null,
    sourceUrl: null,
    locale: 'pt-br',
    upcomingEvents: 7,
  },
  {
    provider: 'TICKETMASTER',
    externalId: 'demo-hans-zimmer',
    name: 'Hans Zimmer Live',
    imageUrl: '/events/noite-sci-fi.png',
    imageAlt: 'Experiencia audiovisual sob um ceu estrelado',
    category: 'Musica',
    genre: 'Classica',
    subGenre: 'Trilha sonora',
    sourceUrl: null,
    locale: 'en-us',
    upcomingEvents: 22,
  },
  {
    provider: 'TICKETMASTER',
    externalId: 'demo-tedx',
    name: 'TEDx Brasil',
    imageUrl: '/events/horizonte-conference.png',
    imageAlt: 'Auditorio moderno preparado para uma conferencia',
    category: 'Conferencia',
    genre: 'Tecnologia',
    subGenre: 'Inovacao',
    sourceUrl: null,
    locale: 'pt-br',
    upcomingEvents: 3,
  },
];
